### ISSUE TITLE
ATR calculation?

### ISSUE THREAD

**Issue by jamesliu1** [t1user/ib_tools#3]
It seems that atr() function in indicators.py uses the current close (instead of the previous close) to calculate "B" and "C"
In this case, "A" is always the max value. 
Is this intentional or just a typo? thanks.

[https://en.wikipedia.org/wiki/Average_true_range](url)

**Comment by t1user** [comment]
You're right. I was a stupid error. It's fixed now. Thanks for bringing it up.
